#!/bin/sh

LAN_IP=$(echo "${1}" | awk '$1 == "[\"ip\"]" {print $2}' | sed -e "s/\"\|\[\|\]//g" | grep "^[0-9]\{1,3\}\.\([0-9]\{1,3\}\.\)\{2\}[0-9]\{1,3\}$")
LAN_MASK=$(echo "${1}" | awk '$1 == "[\"netmask\"]" {print $2}' | sed -e "s/\"\|\[\|\]//g" | grep "^[0-9]\{1,3\}\.\([0-9]\{1,3\}\.\)\{2\}[0-9]\{1,3\}$")

RET_INFO=""

if [ "x$LAN_IP" != "x" -a "x$LAN_MASK" != "x" ]; then

    uci set network.lan.ipaddr="$LAN_IP"
    uci set network.lan.netmask="$LAN_MASK"

    RET_INFO="$RET_INFO,\"ip\":\"$LAN_IP\",\"netmask\":\"$LAN_MASK\""

fi

uci commit network

if [ "$2" = "0" -o "x$2" = "x" ]; then /etc/init.d/network restart; fi

if [ "x$RET_INFO" != "x" ]; then
    echo "{\"ret\":\"OK\"$RET_INFO}"
else
    echo "{\"ret\":\"NOT_CHANGED\",\"reason\":\"no valid args\"}"
fi
