#!/bin/sh

WLAN_DEVICE=$(echo "${1}" | awk '$1 == "[\"device\"]" {print $2}' | sed -e "s/\"\|\[\|\]//g")
WLAN_ENABLED=$(echo "${1}" | awk '$1 == "[\"enabled\"]" {print $2}' | sed -e "s/\"\|\[\|\]//g")
WLAN_CHANNEL=$(echo "${1}" | awk '$1 == "[\"channel\"]" {print $2}' | sed -e "s/\"\|\[\|\]//g" | grep ^[0-9]*$)
WLAN_ENCRYPTION=$(echo "${1}" | awk '$1 == "[\"encryption\"]" {print $2}' | sed -e "s/\"\|\[\|\]//g")
WLAN_SSID=$(echo "${1}" | awk '$1 == "[\"ssid\"]" {print $2}' | sed -e "s/\"\|\[\|\]//g")
WLAN_KEY=$(echo "${1}" | awk '$1 == "[\"key\"]" {print $2}' | sed -e "s/\"\|\[\|\]//g")

RET_INFO=""

# default wlan device
if [ "x$WLAN_DEVICE" = "x" ]; then WLAN_DEVICE="radio0"; fi
RET_INFO="$RET_INFO,\"device\":\"$WLAN_DEVICE\""

# check wlan device
if [ "x`uci get wireless.$WLAN_DEVICE`" = "x" ]; then
    echo "{\"ret\":\"NOT_CHANGED\",\"reason\":\"invalid wlan device\"}"
    exit 1;
fi

# search/match wifi-iface
tempnum=0
ifnum=-1
while [ $tempnum -le 4 ]
do
    if [ "`uci get wireless.@wifi-iface[$tempnum]`" = "wifi-iface" -a \
        "`uci get wireless.@wifi-iface[$tempnum].device`" = "$WLAN_DEVICE" ]; then
        ifnum=$tempnum
    fi
    tempnum=$(($tempnum+1))
done

if [ $ifnum = -1 ]; then
    echo "{\"ret\":\"NOT_CHANGED\",\"reason\":\"iface not found\"}"
    exit 2;
fi

# enable/disable wlan device
if [ "$WLAN_ENABLED" = "0" ]; then
    uci set wireless.$WLAN_DEVICE.disabled="1"
    RET_INFO="$RET_INFO,\"enabled\":\"0\""
elif [ "x$WLAN_ENABLED" != "x" ]; then
    uci set wireless.$WLAN_DEVICE.disabled="0"
    RET_INFO="$RET_INFO,\"enabled\":\"1\""
fi 

# set channel
if [ "x$WLAN_CHANNEL" != "x" ]; then
    uci set wireless.$WLAN_DEVICE.channel="$WLAN_CHANNEL"
    RET_INFO="$RET_INFO,\"channel\":\"$WLAN_CHANNEL\""
fi

# set encryption
if [ "x$WLAN_ENCRYPTION" != "x" ]; then
    RET_INFO="$RET_INFO,\"encryption\":\"$WLAN_ENCRYPTION\""
    if [ "$WLAN_ENCRYPTION" = "none" ]; then
        uci set wireless.@wifi-iface[$ifnum].encryption="none"
    elif [ "$WLAN_ENCRYPTION" = "psk" ]; then
        uci set wireless.@wifi-iface[$ifnum].encryption="psk"
    elif [ "$WLAN_ENCRYPTION" = "psk2" ]; then
        uci set wireless.@wifi-iface[$ifnum].encryption="psk2"
    elif [ "$WLAN_ENCRYPTION" = "psk-mixed" ]; then
        uci set wireless.@wifi-iface[$ifnum].encryption="psk-mixed"
    elif [ "$WLAN_ENCRYPTION" = "wep-open" ]; then
        uci set wireless.@wifi-iface[$ifnum].encryption="wep-open"
    elif [ "$WLAN_ENCRYPTION" = "wep-shared" ]; then
        uci set wireless.@wifi-iface[$ifnum].encryption="wep-shard"
    else
        echo "{\"ret\":\"NOT_CHANGED\",\"reason\":\"invalid wlan encryption\"}"
        exit 3;
    fi
fi

# set ssid
if [ "x$WLAN_SSID" != "x" ]; then
    uci set wireless.@wifi-iface[$ifnum].ssid="$WLAN_SSID"
    RET_INFO="$RET_INFO,\"ssid\":\"$WLAN_SSID\""
fi

# sed key(s)
if [ "x$WLAN_KEY" != "x" ]; then
    uci delete wireless.@wifi-iface[$ifnum].key1
    uci delete wireless.@wifi-iface[$ifnum].key2
    uci delete wireless.@wifi-iface[$ifnum].key3
    uci delete wireless.@wifi-iface[$ifnum].key4
    if [ "$WLAN_ENCRYPTION" = "wep-open" -o "$WLAN_ENCRYPTION" = "wep-shared" ]; then
        if [ "`echo $KEY | awk -F ',' '{print NF}'`" = '1' ]; then
            uci set wireless.@wifi-iface[$ifnum].key="1"
            uci set wireless.@wifi-iface[$ifnum].key1="s:$WLAN_KEY"
        else
            KEY_NUM="$(echo $WLAN_KEY | awk -F ',' '$1~/^[1-4]$/ {print $1}')"
            if [ "x$KEY_NUM" != "x" ]; then
                uci set wireless.@wifi-iface[$ifnum].key="$KEY_NUM"
            else
                uci set wireless.@wifi-iface[$ifnum].key="1"
            fi
            uci set wireless.@wifi-iface[$ifnum].key1="$(echo $WLAN_KEY | awk -F ',' '$2!~/^$/ {print "s:"$2}')"
            uci set wireless.@wifi-iface[$ifnum].key2="$(echo $WLAN_KEY | awk -F ',' '$3!~/^$/ {print "s:"$3}')"
            uci set wireless.@wifi-iface[$ifnum].key3="$(echo $WLAN_KEY | awk -F ',' '$4!~/^$/ {print "s:"$4}')"
            uci set wireless.@wifi-iface[$ifnum].key4="$(echo $WLAN_KEY | awk -F ',' '$5!~/^$/ {print "s:"$5}')"
        fi
    else
        uci set wireless.@wifi-iface[$ifnum].key="$WLAN_KEY"
    fi
    RET_INFO="$RET_INFO,\"key\":\"$WLAN_KEY\""
fi

uci commit wireless

if [ "$2" = "0" -o "x$2" = "x" ]; then wifi; fi

if [ "x$RET_INFO" != "x" ]; then
    echo "{\"ret\":\"OK\"$RET_INFO}"
else
    echo "{\"ret\":\"NOT_CHANGED\",\"reason\":\"no valid args\"}"
fi
