#!/bin/sh 

. /usr/share/libubox/jshn.sh

DEBUG=$(uci get cgirpc.debug.enabled)

RPC_FUNC_PATH=$(uci get cgirpc.common.rpc_func_path)
if [ "x$RPC_FUNC_PATH" = "x" ]; then
RPC_FUNC_PATH='/usr/lib/cgi-rpc/rpc-func'
fi

COMMON_FUNC_PATH=$(uci get cgirpc.common.common_func_path)
if [ "x$COMMON_FUNC_PATH" = "x" ]; then
COMMON_FUNC_PATH='/usr/bin'
fi

json_load $(echo $QUERY_STRING | $COMMON_FUNC_PATH/urldecode)

json_get_var METHOD "method"
json_get_var TARGET "target"

echo "Content-type: text/json"
echo ""

if [ "$DEBUG" != "0" -a "x$DEBUG" != "x" ]; then
echo "+-+-------Debug JSON--------+-+"
echo "Translated query string: $TRANS_QS"
echo "Method: $METHOD"
echo "Target: $TARGET"
echo "Run script: rpc-func/$METHOD/$TARGET"
echo "+-+-------------------------+-+"
fi

. $RPC_FUNC_PATH/$METHOD/$TARGET $DEBUG
