#!/bin/sh

LISTFILE=/tmp/cgi-rpc.firewall.blocklist
cat /dev/null > $LISTFILE

count=0
while [ "x$(uci get clientlist.@client[$count] 2>&1 1>/dev/null)" = "x" ]; do
    MAC="$(uci get clientlist.@client[$count].mac | tr 'a-f' 'A-F')"
    DISABLED="$(uci get clientlist.@client[$count].disabled)"
    POLICY="$(uci get clientlist.@client[$count].policy)"
    if [ "$DISABLED" = "1" ]; then

        echo "iptables -t mangle -I FORWARD -m mac --mac-source $MAC -j DROP" >> $LISTFILE

    else

        [ "x$POLICY" != "x" ] && echo "iptables -t mangle -I FORWARD -m mac --mac-source $MAC -m time --timestart 00:00:00 --timestop 23:59:59 -j DROP" >> $LISTFILE
        
        for each in $POLICY; do
            cnt=0
            scnt=-1
            flag=0
            while [ "x$(uci get blocklist.@policy[$cnt] 2>&1 1>/dev/null)" = "x" -a "flag" != "1" ]; do
                [ "$(uci get blocklist.@policy[$cnt].id)" = "$each" ] && flag=1 && scnt=$cnt
                cnt=$(($cnt+1))
            done
            if [ "$flag" != "1" -o "$scnt" = "-1" ]; then
                BLOCKLIST=
                TIMERANGE=
                uci del_list clientlist.@client[$count].policy="$each"
            else
                BLOCKLIST="$(uci get blocklist.@policy[$scnt].site)"
                TIMERANGE="$(uci get blocklist.@policy[$scnt].time)"
            fi

            for each_time in $TIMERANGE; do
                echo "iptables -t mangle -I FORWARD -m mac --mac-source $MAC -m time --timestart ${each_time%-*} --timestop ${each_time#*-} -j ACCEPT" >> $LISTFILE
                for each_site in $BLOCKLIST; do
                    echo "iptables -t mangle -I FORWARD -m mac --mac-source $MAC -m time --timestart ${each_time%-*} --timestop ${each_time#*-} -m string --string $each_site --algo kmp -j DROP" >> $LISTFILE
                done
            done
        done
    fi
    count=$(($count+1))
done

[ ! -L /etc/firewall.blocklist ] && rm -rf /etc/firewall.blocklist && ln -s $LISTFILE /etc/firewall.blocklist

/etc/init.d/firewall restart > /dev/null 2>&1
